### PR TITLE
Fixes #51.  Closing active data and hint files on Medea#close, plus other Windows fixes.

### LINKED ISSUE #51: Re-opening a closed database crashes on Windows.
```js
var medea = require('medea');

var db = medea();

db.open(function() {
  db.close(function() {
    db.open(function(err) {
      console.error(err);
    });
  });
});
```

```
$ node test.js
{ [Error: EPERM, open 'c:\Users\Kevin Swiber\projects\medea-break\medea\1.medea.data']
  errno: 50,
  code: 'EPERM',
  path: 'c:\\Users\\Kevin Swiber\\projects\\medea-break\\medea\\1.medea.data' }
```

### PR DESCRIPTION
**Pull request by kevinswiber**

### CODE REVIEW

**Comment by kevinswiber** [comment]
Look at the comments on #51.  In the following scenario:

1. Unlink a file.
2. Read that file's directory.

Windows returns the file that has been deleted. Taking any operation on that file, of course, returns an error.  In this case, it's `EPERM`.  It's not ideal, but in this PR, there is some checking to see if files are valid before reading them.  We check if there's an `EPERM` error and then omit it.

**Comment by kevinswiber** [comment]
This is the first time I've seen the AppVeyor integration work.  Please ignore for now.  All tests are not passing on Windows yet.  Medea#destroy tests have some issues.

**Comment by kevinswiber** [comment]
@AdamMagaluk I know you have a Windows VM handy.  When you get a chance, will you review this PR?

**Comment by AdamMagaluk** [comment]
Seeing these issues on Windows 7:

```
 1) Medea.destroy folder with medea-files & lock-file deletes the folder:
    Uncaught AssertionError: true == false
     at C:\Users\IEUser\medea\test\medea_destroy_test.js:74:16
     at C:\Users\IEUser\medea\destroy.js:36:11
     at Object.oncomplete (fs.js:108:15)

 2) Medea#destroy initialized and closed db deletes the folder:
    Uncaught TypeError: Cannot call method 'closeForWriting' of null
     at Medea.close (C:\Users\IEUser\medea\medea.js:263:15)
     at C:\Users\IEUser\medea\test\medea_destroy_test.js:105:16
     at C:\Users\IEUser\medea\medea.js:290:14
     at Medea._getActiveFile (C:\Users\IEUser\medea\medea.js:464:12)
     at Medea.put (C:\Users\IEUser\medea\medea.js:288:8)
     at C:\Users\IEUser\medea\test\medea_destroy_test.js:104:14
     at C:\Users\IEUser\medea\node_modules\async\lib\async.js:254:17
     at C:\Users\IEUser\medea\node_modules\async\lib\async.js:151:21
     at C:\Users\IEUser\medea\node_modules\async\lib\async.js:251:21
     at C:\Users\IEUser\medea\node_modules\async\lib\async.js:615:34
     at C:\Users\IEUser\medea\medea.js:138:14
     at C:\Users\IEUser\medea\medea.js:196:15
     at Object.oncomplete (fs.js:108:15)

 3) Medea#open() when there are empty hint & data-files "before all" hook:
    Uncaught TypeError: Bad argument
     at Object.fs.close (fs.js:405:11)
     at C:\Users\IEUser\medea\test\medea_test.js:332:14
     at Object.oncomplete (fs.js:108:15)
```

**Comment by kevinswiber** [comment]
@AdamMagaluk Yes, `Medea#destroy` is still a little borked.  Can you check out compaction?

**Comment by AdamMagaluk** [comment]
Gotcha, both running compaction standalone and with the zetta init compaction process work now. No more fsync on startup.

**Pull request merged**
